Repository ruthlennonatu/wolverine22, pull requests merged in 2022-11, with the labels that each got.

#44 Resolves #gh-42 via basic_architecture.txt
  basic_architecture.txt
Labels: documentation

#91 PasswordEncryptionService.java
  PasswordEncryptionService.java
Labels: good first issue

#145 WolverinFitnessForAllGroupClassesUML.uxf
  WolverineFitnessForAllGroupClassesUML.uxf
Labels: documentation

#146 SercurePayments.java
  SercurePayments.java
Labels: good first issue

#155 How to push to git.dox
  How to push to git.docx
Labels: bug

#126 Gh79 wip
  Database_L00134231/READMEFiles/README_addAdmin.md
  addAdmin.java
Labels: good first issue

#166 CardFormTest.handleCardIOResponse
  CardFormTest.handleCardIOResponse
Labels: good first issue

#167 PayPalCreditCardAgent.onActivityResult
  PayPalCreditCardAgent.onActivityResult
Labels: good first issue

#169 scansAmexCards.java
  scansAmexCards.java
Labels: good first issue
